version: "3"
services:
  samba:
    build:
      context: .
    container_name: samba
    image: samba
    expose:
      - 137/udp
      - 138/udp
      - 139/tcp
      - 445/tcp
    volumes:
      - /mnt/shared:/shared:rw
      - /mnt/shared/media:/media:rw
    network_mode: host
